### PR TITLE
Fixed parsing when no white char before amount/size of the dish

### PR DESCRIPTION
**Pull request by PiotrDabrowskey**
I fixed a problem, when name of a dish is not separated from amount or size of the dish by any white character.

Explanation of the problem: [out.txt](https://github.com/pawelabrams/pwr-sks-cli/files/519700/out.txt)

Site causing the problem: [site.txt](https://github.com/pawelabrams/pwr-sks-cli/files/519704/site.txt)

### CODE REVIEW

**Comment by pawelabrams** [comment]
Approved and appreciated!

**Comment by pawelabrams** [comment]
Hah, SKS trolled us yet again: today's menu includes "Frytki 7mm" – and the old version got it better. If I have some free time, I will try to come up with some solution (possibly `\d+(g|ml)` would suffice).

**Comment by PiotrDabrowskey** [comment]
I'd say that's not a problem. "7mm" is also a size/amount of the dish. They present it the same way in their mobile app: 
screenshot_20161011-204522 png

**Comment by pawelabrams** [comment]
Valid point. The solution stays.

**Pull request merged**
